### ISSUE TITLE
Improve accessibility by choosing proven GIS color palette

### ISSUE THREAD

**Issue by ergophobe** [walkerke/education_map#3]
Fascinating map, but difficult accessibility. There are a lot GIS people who have thought long and hard about color schemes for mapping and looking to them might improve this assuming you can set the colors.

If you look at the legend in grey scale, you can see that the middle term "some college" is the brightest. 

So from a grey-scale point of view, you start dark, go bright, then go dark (see screenshot). That means that for someone like me, I really can't extract a lot of information from this.

![map-legend](https://cloud.githubusercontent.com/assets/1359523/24108880/398fddc6-0d4c-11e7-922f-472bed233291.png)

Ideally, what you would do is go from a blue with low luminosity to a red with high luminosity. That would let people with full color vision use color, but would make the map usable to the 8% of males with color impairment (much lower among females).

Here are some suggested palettes for scientific graphics that, as a colorblind person, I agree work well and have little ambiguity
https://betterfigures.org/2015/06/23/picking-a-colour-scale-for-scientific-graphics/

Cindy Brewer has done research for 30 years on presenting maps (at least her publications include a 1986 postcard for choosing map colors for red-green impaired individuals) and she created ColorBrewer to help with choosing map colors.
http://colorbrewer2.org/#type=qualitative&scheme=Set3&n=4
http://colorbrewer2.org/learnmore/schemes_full.html
http://www.personal.psu.edu/cab38/Pub_scans/Brewer_pubs.html

Somewhere in there should be a color scheme that would work with your data and be more broadly accessible.

**Comment by walkerke** [comment]
Thank you for your feedback!  You are correct that my chosen categorical palette, ColorBrewer Set1, isn't colorblind-friendly.  I've committed the map here that uses RdYlBu instead: http://personal.tcu.edu/kylewalker/maps/education/colorsafe/.

**Comment by ergophobe** [comment]
Nice! Definitely easier to visualize. Grad and Bachelor's now look similar and Less than high school looks very different. So now the map gives me a really nice visual contrast between highly educated and less educated.
